const {
  Document, Packer, Paragraph, TextRun, Table, TableRow, TableCell,
  Header, Footer, AlignmentType, HeadingLevel, BorderStyle, WidthType,
  ShadingType, VerticalAlign, LevelFormat, TabStopType, TabStopPosition, PageBreak
} = require('docx');
const fs = require('fs');

const C = {
  bg: "0C0C12", acc: "FF6B35", grn: "16A34A", red: "DC2626",
  pur: "7C3AED", blu: "2563EB", amb: "D97706",
  dark: "1A1A2E", slate: "334155", white: "F2F1EA",
  codbg: "0D1117", codhi: "58A6FF", codstr: "A5D6FF",
  codcmt: "8B949E", codnum: "79C0FF", codkey: "FF7B72",
};

const nb = () => ({ style: BorderStyle.NONE, size: 0, color: "FFFFFF" });
const noBdr = () => ({ top: nb(), bottom: nb(), left: nb(), right: nb() });
const bdr = (c = "2A2A3C") => ({ style: BorderStyle.SINGLE, size: 1, color: c });
const bdrs = (c = "2A2A3C") => ({ top: bdr(c), bottom: bdr(c), left: bdr(c), right: bdr(c) });
const cm = { top: 80, bottom: 80, left: 140, right: 140 };
const cmw = { top: 110, bottom: 110, left: 180, right: 180 };

const sp = (n = 100) => new Paragraph({ spacing: { before: 0, after: 0 }, children: [new TextRun({ text: " ", size: 2 })] });
const pgBreak = () => new Paragraph({ children: [new PageBreak()] });
const hr = (col = "2A2A3C", sz = 6) => new Paragraph({
  border: { bottom: { style: BorderStyle.SINGLE, size: sz, color: col, space: 1 } },
  spacing: { before: 60, after: 60 }, children: []
});

const h1 = (t) => new Paragraph({
  heading: HeadingLevel.HEADING_1, spacing: { before: 320, after: 120 },
  children: [new TextRun({ text: t, font: "Consolas", size: 40, bold: true, color: C.white })]
});
const h2 = (t, col = C.acc) => new Paragraph({
  heading: HeadingLevel.HEADING_2, spacing: { before: 260, after: 80 },
  children: [new TextRun({ text: t, font: "Arial", size: 26, bold: true, color: col })]
});
const h3 = (t) => new Paragraph({
  heading: HeadingLevel.HEADING_3, spacing: { before: 200, after: 60 },
  children: [new TextRun({ text: t, font: "Arial", size: 22, bold: true, color: C.white })]
});
const body = (t, opts = {}) => new Paragraph({
  spacing: { before: 50, after: 70, line: 290 },
  children: [new TextRun({ text: t, font: "Arial", size: 20, color: opts.color || "CCCCCC", bold: opts.bold || false, italics: opts.italic || false })]
});
const warn = (t) => new Paragraph({
  spacing: { before: 80, after: 80 },
  shading: { fill: "2D1A00", type: ShadingType.CLEAR },
  border: { right: nb(), left: { style: BorderStyle.SINGLE, size: 16, color: C.amb, space: 8 } },
  indent: { left: 200, right: 200 },
  children: [new TextRun({ text: "⚠  " + t, font: "Arial", size: 20, color: "FCD34D" })]
});
const good = (t) => new Paragraph({
  spacing: { before: 80, after: 80 },
  shading: { fill: "052E16", type: ShadingType.CLEAR },
  border: { right: nb(), left: { style: BorderStyle.SINGLE, size: 16, color: C.grn, space: 8 } },
  indent: { left: 200, right: 200 },
  children: [new TextRun({ text: "✓  " + t, font: "Arial", size: 20, color: "86EFAC" })]
});
const bullet = (t, bold = false) => new Paragraph({
  numbering: { reference: "bul", level: 0 }, spacing: { before: 40, after: 40 },
  children: [new TextRun({ text: t, font: "Arial", size: 20, color: "CCCCCC", bold })]
});
const num = (t) => new Paragraph({
  numbering: { reference: "nums", level: 0 }, spacing: { before: 50, after: 50 },
  children: [new TextRun({ text: t, font: "Arial", size: 20, color: "CCCCCC" })]
});
const fileTag = (t) => new Paragraph({
  spacing: { before: 140, after: 40 },
  children: [
    new TextRun({ text: "📄  ", font: "Arial", size: 18 }),
    new TextRun({ text: t, font: "Consolas", size: 18, bold: true, color: C.acc }),
  ]
});

// Code block renderer — GitHub dark theme
const code = (lines) => {
  const lineStyle = (line) => {
    // Simple syntax hint coloring per line prefix
    const l = line.trim();
    const isComment = l.startsWith("//") || l.startsWith("#") || l.startsWith("/*") || l.startsWith("*");
    const isImport = l.startsWith("import") || l.startsWith("export");
    const isReturn = l.startsWith("return") || l.startsWith("const ") || l.startsWith("let ") || l.startsWith("async ");
    const color = isComment ? C.codcmt : isImport ? C.codhi : C.codstr;
    return color;
  };
  return [
    new Paragraph({
      spacing: { before: 80, after: 0 },
      shading: { fill: C.codbg, type: ShadingType.CLEAR },
      border: {
        top: bdr("30363D"), right: bdr("30363D"), bottom: bdr("30363D"),
        left: { style: BorderStyle.SINGLE, size: 20, color: C.acc, space: 4 }
      },
      indent: { left: 160, right: 160 },
      children: []
    }),
    ...lines.map(line => new Paragraph({
      spacing: { before: 0, after: 0 },
      shading: { fill: C.codbg, type: ShadingType.CLEAR },
      border: { right: bdr("30363D"), left: { style: BorderStyle.SINGLE, size: 20, color: C.acc, space: 4 } },
      indent: { left: 280, right: 200 },
      children: [new TextRun({
        text: line === "" ? " " : line,
        font: "Consolas", size: 17,
        color: lineStyle(line),
      })]
    })),
    new Paragraph({
      spacing: { before: 0, after: 80 },
      shading: { fill: C.codbg, type: ShadingType.CLEAR },
      border: { bottom: bdr("30363D"), left: { style: BorderStyle.SINGLE, size: 20, color: C.acc, space: 4 }, right: bdr("30363D") },
      indent: { left: 160, right: 160 },
      children: []
    }),
  ];
};

// ─── COVER ────────────────────────────────────────────────────────────────────
const cover = [
  sp(), sp(), sp(), sp(), sp(), sp(), sp(), sp(), sp(), sp(),
  new Paragraph({
    alignment: AlignmentType.CENTER, spacing: { before: 0, after: 80 },
    shading: { fill: C.codbg, type: ShadingType.CLEAR },
    children: [new TextRun({ text: "ARTHA", font: "Consolas", size: 120, bold: true, color: C.acc })]
  }),
  new Paragraph({
    alignment: AlignmentType.CENTER, spacing: { before: 0, after: 60 },
    shading: { fill: C.codbg, type: ShadingType.CLEAR },
    children: [new TextRun({ text: "COMPLETE WORKING CODEBASE", font: "Consolas", size: 28, color: "444466" })]
  }),
  hr(C.acc, 12),
  sp(),
  new Paragraph({
    alignment: AlignmentType.CENTER, spacing: { before: 40, after: 40 },
    children: [new TextRun({ text: "Every file. Complete code. Real data. Actually works.", font: "Arial", size: 22, italics: true, color: "888888" })]
  }),
  sp(), sp(),
  new Table({
    width: { size: 8000, type: WidthType.DXA }, columnWidths: [2400, 5600],
    borders: { top: nb(), bottom: nb(), left: nb(), right: nb(), insideH: bdr("222233"), insideV: nb() },
    rows: [
      ["Framework",   "React Native · Expo SDK 56 · TypeScript"],
      ["Database",    "expo-sqlite v14+ (async, on-device, private)"],
      ["AI",          "Claude API (claude-haiku-4-5 — cheapest, fastest)"],
      ["Navigation",  "Bottom Tabs + Stack Navigator (native feel)"],
      ["State",       "Zustand (lightweight, no boilerplate)"],
      ["Build",       "EAS Build → APK (Android) / IPA (iOS)"],
      ["Cost",        "~₹0 to build · ~₹150/month to run"],
    ].map(([k, v]) => new TableRow({ children: [
      new TableCell({ borders: noBdr(), margins: { top: 80, bottom: 80, left: 0, right: 120 },
        children: [new Paragraph({ children: [new TextRun({ text: k, font: "Consolas", size: 18, color: "666688", bold: true })] })] }),
      new TableCell({ borders: noBdr(), margins: { top: 80, bottom: 80, left: 120, right: 0 },
        children: [new Paragraph({ children: [new TextRun({ text: v, font: "Arial", size: 18, color: "AAAAAA" })] })] }),
    ]}))
  }),
  pgBreak(),
];

// ─── WHY IT FEELS LIKE HTML ───────────────────────────────────────────────────
const s0 = [
  h1("Why It Feels Like 'HTML in a Box' — And How We Fix It"),
  hr(C.acc, 4), sp(),
  body("React Native IS native. It compiles to real iOS/Android views — not a WebView. If the app feels like a website it means one of four things went wrong. We fix all four."),
  sp(),
  new Table({
    width: { size: 9360, type: WidthType.DXA }, columnWidths: [3600, 2400, 3360],
    rows: [
      new TableRow({ children: ["Problem", "Symptom", "Fix in this guide"].map(t => new TableCell({
        borders: bdrs("333355"), shading: { fill: "0D1117", type: ShadingType.CLEAR }, margins: cm,
        children: [new Paragraph({ children: [new TextRun({ text: t, font: "Arial", size: 18, bold: true, color: C.acc })] })]
      })) }),
      ...[
        ["No real data flow", "Numbers are hardcoded, nothing updates after you add a transaction", "Every screen reads live from SQLite via useEffect + Zustand"],
        ["Engines not connected to UI", "Safe to Spend shows ₹4,230 always — the engine exists but UI ignores it", "Screens call engines directly, re-run on every focus"],
        ["Generic styling", "No platform-specific feel, looks like a web form", "Platform.select(), native shadows, haptic feedback, proper fonts"],
        ["No loading/error states", "Blank screens on first open, crashes on empty DB", "Skeleton loaders, empty states, error boundaries on every screen"],
      ].map(([p, s, f]) => new TableRow({ children: [p, s, f].map((t, i) => new TableCell({
        borders: bdrs("222233"), shading: { fill: i === 0 ? "0D1117" : "000000", type: ShadingType.CLEAR }, margins: cm,
        children: [new Paragraph({ children: [new TextRun({ text: t, font: "Arial", size: 18, color: i === 2 ? "86EFAC" : "AAAAAA" })] })]
      })) }))
    ]
  }),
  sp(), pgBreak(),
];

// ─── PACKAGE.JSON ─────────────────────────────────────────────────────────────
const s1 = [
  h1("File 1 — package.json"),
  hr(C.acc, 4), sp(),
  body("Start here. Delete your current package.json and replace it completely. Then run npm install."),
  sp(),
  fileTag("package.json"),
  ...code([
    '{',
    '  "name": "artha",',
    '  "version": "1.0.0",',
    '  "main": "node_modules/expo/AppEntry.js",',
    '  "scripts": {',
    '    "start":   "expo start",',
    '    "android": "expo start --android",',
    '    "ios":     "expo start --ios",',
    '    "build:android": "eas build --platform android --profile preview"',
    '  },',
    '  "dependencies": {',
    '    "expo":                              "~56.0.0",',
    '    "expo-status-bar":                   "~2.0.0",',
    '    "expo-sqlite":                       "~15.1.2",',
    '    "expo-notifications":                "~0.29.0",',
    '    "expo-secure-store":                 "~14.0.0",',
    '    "expo-haptics":                      "~14.0.0",',
    '    "expo-font":                         "~13.0.0",',
    '    "@expo-google-fonts/dm-sans":        "^0.2.3",',
    '    "@expo-google-fonts/space-grotesk":  "^0.2.3",',
    '    "@expo/vector-icons":                "^14.0.0",',
    '    "@react-navigation/native":          "^7.0.0",',
    '    "@react-navigation/bottom-tabs":     "^7.0.0",',
    '    "@react-navigation/stack":           "^7.0.0",',
    '    "react-native-screens":              "~4.4.0",',
    '    "react-native-safe-area-context":    "4.12.0",',
    '    "react-native-gesture-handler":      "~2.21.0",',
    '    "react-native-reanimated":           "~3.17.0",',
    '    "react-native-svg":                  "15.9.0",',
    '    "victory-native":                    "^41.0.0",',
    '    "zustand":                           "^5.0.0",',
    '    "@tanstack/react-query":             "^5.0.0",',
    '    "date-fns":                          "^4.1.0",',
    '    "react":                             "18.3.2",',
    '    "react-native":                      "0.76.5"',
    '  },',
    '  "devDependencies": {',
    '    "@babel/core":     "^7.25.0",',
    '    "typescript":      "^5.3.0",',
    '    "@types/react":    "~18.3.0"',
    '  }',
    '}',
  ]),
  sp(),
  fileTag("babel.config.js"),
  ...code([
    "module.exports = function(api) {",
    "  api.cache(true);",
    "  return {",
    "    presets: ['babel-preset-expo'],",
    "    plugins: ['react-native-reanimated/plugin'],",
    "  };",
    "};",
  ]),
  sp(), pgBreak(),
];

// ─── THEME ────────────────────────────────────────────────────────────────────
const s2 = [
  h1("File 2 — theme/index.ts  (Complete Design System)"),
  hr(C.acc, 4), sp(),
  body("One file exports everything: colors, spacing, typography, shadow styles, and card styles. No hex codes anywhere else in the codebase."),
  sp(),
  fileTag("theme/index.ts"),
  ...code([
    "import { Platform, StyleSheet } from 'react-native';",
    "",
    "// ── COLORS ──────────────────────────────────────────────────────",
    "export const colors = {",
    "  // Backgrounds",
    "  bg:       '#0C0C12',   // app background",
    "  s1:       '#141420',   // card surface",
    "  s2:       '#1C1C2A',   // inner card / pill",
    "  s3:       '#242432',   // input background",
    "  s4:       '#2C2C3C',   // pressed state",
    "  border:   '#2A2A3C',",
    "",
    "  // Semantic",
    "  accent:   '#FF6B35',   // Artha orange — primary CTA",
    "  accent2:  '#FFB347',   // amber — secondary/warning",
    "  green:    '#22C55E',   // safe / success",
    "  red:      '#EF4444',   // danger",
    "  purple:   '#A855F7',   // Jugaad",
    "  blue:     '#3B82F6',   // info",
    "  cyan:     '#06B6D4',   // gig / income",
    "",
    "  // Text",
    "  text:     '#F2F1EA',",
    "  muted:    '#8B8A9A',",
    "  subtle:   '#4A4A5A',",
    "};",
    "",
    "// ── SPACING ─────────────────────────────────────────────────────",
    "export const spacing = {",
    "  xs: 4, sm: 8, md: 12, base: 16, lg: 20, xl: 24, xxl: 32,",
    "};",
    "",
    "// ── RADIUS ──────────────────────────────────────────────────────",
    "export const radius = {",
    "  sm: 8, md: 12, lg: 16, xl: 20, full: 999,",
    "};",
    "",
    "// ── TYPOGRAPHY ──────────────────────────────────────────────────",
    "export const type = {",
    "  // headings use Space Grotesk",
    "  h1: { fontFamily: 'SpaceGrotesk_700Bold', fontSize: 28, color: colors.text, lineHeight: 34 },",
    "  h2: { fontFamily: 'SpaceGrotesk_700Bold', fontSize: 22, color: colors.text, lineHeight: 28 },",
    "  h3: { fontFamily: 'SpaceGrotesk_600SemiBold', fontSize: 17, color: colors.text, lineHeight: 22 },",
    "  // body uses DM Sans",
    "  body: { fontFamily: 'DMSans_400Regular', fontSize: 14, color: colors.muted, lineHeight: 20 },",
    "  bodyMd: { fontFamily: 'DMSans_500Medium', fontSize: 14, color: colors.text, lineHeight: 20 },",
    "  label: { fontFamily: 'DMSans_500Medium', fontSize: 11, color: colors.muted, letterSpacing: 0.8, textTransform: 'uppercase' },",
    "  // big numbers",
    "  hero: { fontFamily: 'SpaceGrotesk_700Bold', fontSize: 48, lineHeight: 54 },",
    "  big:  { fontFamily: 'SpaceGrotesk_700Bold', fontSize: 32, lineHeight: 38 },",
    "  num:  { fontFamily: 'SpaceGrotesk_600SemiBold', fontSize: 20, lineHeight: 26 },",
    "} as const;",
    "",
    "// ── SHADOWS ─────────────────────────────────────────────────────",
    "export const shadow = Platform.select({",
    "  ios: {",
    "    shadowColor: '#000',",
    "    shadowOffset: { width: 0, height: 4 },",
    "    shadowOpacity: 0.3,",
    "    shadowRadius: 8,",
    "  },",
    "  android: { elevation: 6 },",
    "  default: {},",
    "});",
    "",
    "// ── REUSABLE CARD STYLES ─────────────────────────────────────────",
    "export const card = StyleSheet.create({",
    "  base: {",
    "    backgroundColor: colors.s1,",
    "    borderRadius: radius.lg,",
    "    padding: spacing.base,",
    "    borderWidth: 1,",
    "    borderColor: colors.border,",
    "    marginBottom: spacing.md,",
    "    ...shadow,",
    "  },",
    "  inner: {",
    "    backgroundColor: colors.s2,",
    "    borderRadius: radius.md,",
    "    padding: spacing.md,",
    "  },",
    "  danger: {",
    "    backgroundColor: '#1A0808',",
    "    borderRadius: radius.lg,",
    "    padding: spacing.base,",
    "    borderWidth: 1,",
    "    borderColor: '#5C1A1A',",
    "    marginBottom: spacing.md,",
    "  },",
    "  warn: {",
    "    backgroundColor: '#1A1000',",
    "    borderRadius: radius.lg,",
    "    padding: spacing.base,",
    "    borderWidth: 1,",
    "    borderColor: '#5C3A00',",
    "    marginBottom: spacing.md,",
    "  },",
    "  success: {",
    "    backgroundColor: '#0A1A0E',",
    "    borderRadius: radius.lg,",
    "    padding: spacing.base,",
    "    borderWidth: 1,",
    "    borderColor: '#1A5C2A',",
    "    marginBottom: spacing.md,",
    "  },",
    "});",
  ]),
  sp(), pgBreak(),
];

// ─── DB SCHEMA ────────────────────────────────────────────────────────────────
const s3 = [
  h1("File 3 — db/schema.ts  (Database Init)"),
  hr(C.acc, 4), sp(),
  body("This runs once at app start. It creates all tables if they don't exist. Safe to re-run — uses IF NOT EXISTS everywhere."),
  sp(),
  fileTag("db/schema.ts"),
  ...code([
    "import * as SQLite from 'expo-sqlite';",
    "",
    "let _db: SQLite.SQLiteDatabase | null = null;",
    "",
    "export async function getDB(): Promise<SQLite.SQLiteDatabase> {",
    "  if (_db) return _db;",
    "  _db = await SQLite.openDatabaseAsync('artha.db');",
    "  return _db;",
    "}",
    "",
    "export async function initDB(): Promise<void> {",
    "  const db = await getDB();",
    "",
    "  // Enable WAL mode for better concurrent read performance",
    "  await db.execAsync('PRAGMA journal_mode = WAL;');",
    "",
    "  await db.execAsync(`",
    "",
    "    -- ── USER PROFILE ──────────────────────────────────────────",
    "    CREATE TABLE IF NOT EXISTS profile (",
    "      id            INTEGER PRIMARY KEY DEFAULT 1,",
    "      name          TEXT    DEFAULT 'You',",
    "      city          TEXT    DEFAULT 'Hyderabad',",
    "      income_type   TEXT    DEFAULT 'salary',  -- salary | gig | mixed",
    "      monthly_income REAL   DEFAULT 0,",
    "      salary_day    INTEGER DEFAULT 28,         -- day of month",
    "      current_balance REAL  DEFAULT 0,",
    "      safety_pct    REAL    DEFAULT 5,          -- % buffer",
    "      claude_key    TEXT    DEFAULT ''",
    "    );",
    "    INSERT OR IGNORE INTO profile (id) VALUES (1);",
    "",
    "    -- ── TRANSACTIONS ──────────────────────────────────────────",
    "    CREATE TABLE IF NOT EXISTS transactions (",
    "      id           INTEGER PRIMARY KEY AUTOINCREMENT,",
    "      amount       REAL    NOT NULL,",
    "      type         TEXT    NOT NULL,  -- debit | credit",
    "      category     TEXT    NOT NULL DEFAULT 'other',",
    "      merchant     TEXT    DEFAULT '',",
    "      note         TEXT    DEFAULT '',",
    "      txn_date     TEXT    NOT NULL,  -- ISO string",
    "      is_recurring INTEGER DEFAULT 0,",
    "      member_id    INTEGER DEFAULT 0, -- 0 = self",
    "      created_at   TEXT    DEFAULT (datetime('now'))",
    "    );",
    "",
    "    -- ── RECURRING BILLS ───────────────────────────────────────",
    "    CREATE TABLE IF NOT EXISTS bills (",
    "      id           INTEGER PRIMARY KEY AUTOINCREMENT,",
    "      name         TEXT    NOT NULL,",
    "      amount       REAL    NOT NULL,",
    "      category     TEXT    NOT NULL DEFAULT 'other',",
    "      due_day      INTEGER NOT NULL,  -- 1–31",
    "      active       INTEGER DEFAULT 1,",
    "      color        TEXT    DEFAULT '#EF4444'",
    "    );",
    "",
    "    -- ── GIG INVOICES ──────────────────────────────────────────",
    "    CREATE TABLE IF NOT EXISTS invoices (",
    "      id           INTEGER PRIMARY KEY AUTOINCREMENT,",
    "      client       TEXT    NOT NULL,",
    "      project      TEXT    NOT NULL,",
    "      amount       REAL    NOT NULL,",
    "      status       TEXT    DEFAULT 'pending', -- pending|collected|overdue",
    "      due_date     TEXT    NOT NULL,",
    "      raised_date  TEXT    DEFAULT (date('now'))",
    "    );",
    "",
    "    -- ── FAMILY MEMBERS ────────────────────────────────────────",
    "    CREATE TABLE IF NOT EXISTS members (",
    "      id            INTEGER PRIMARY KEY AUTOINCREMENT,",
    "      name          TEXT    NOT NULL,",
    "      initials      TEXT    NOT NULL,",
    "      monthly_limit REAL    NOT NULL DEFAULT 0,",
    "      color         TEXT    DEFAULT '#3B82F6'",
    "    );",
    "",
    "    -- ── SAVINGS JARS ──────────────────────────────────────────",
    "    CREATE TABLE IF NOT EXISTS jars (",
    "      id           INTEGER PRIMARY KEY AUTOINCREMENT,",
    "      name         TEXT    NOT NULL,",
    "      target       REAL    NOT NULL,",
    "      saved        REAL    DEFAULT 0,",
    "      color        TEXT    DEFAULT '#22C55E',",
    "      icon         TEXT    DEFAULT '🪙',",
    "      auto_save    REAL    DEFAULT 0",
    "    );",
    "",
    "    -- ── AI COACH CHAT ─────────────────────────────────────────",
    "    CREATE TABLE IF NOT EXISTS coach_chat (",
    "      id           INTEGER PRIMARY KEY AUTOINCREMENT,",
    "      role         TEXT    NOT NULL,  -- user | assistant",
    "      content      TEXT    NOT NULL,",
    "      created_at   TEXT    DEFAULT (datetime('now'))",
    "    );",
    "",
    "    -- ── DOOM EVENTS (for history) ──────────────────────────────",
    "    CREATE TABLE IF NOT EXISTS doom_events (",
    "      id           INTEGER PRIMARY KEY AUTOINCREMENT,",
    "      txn_count    INTEGER NOT NULL,",
    "      total_amount REAL    NOT NULL,",
    "      detected_at  TEXT    DEFAULT (datetime('now')),",
    "      resolved     INTEGER DEFAULT 0",
    "    );",
    "",
    "  `);",
    "}",
  ]),
  sp(), pgBreak(),
];

// ─── DB QUERIES ───────────────────────────────────────────────────────────────
const s4 = [
  h1("File 4 — db/queries.ts  (All Database Operations)"),
  hr(C.acc, 4), sp(),
  body("Every screen calls these functions. Never write raw SQL in a screen component. All reads and writes go through here."),
  sp(),
  fileTag("db/queries.ts"),
  ...code([
    "import { getDB } from './schema';",
    "import { format, startOfMonth, endOfMonth } from 'date-fns';",
    "",
    "// ── PROFILE ──────────────────────────────────────────────────────",
    "export async function getProfile() {",
    "  const db = await getDB();",
    "  return db.getFirstAsync<Profile>('SELECT * FROM profile WHERE id = 1');",
    "}",
    "",
    "export async function updateProfile(data: Partial<Profile>) {",
    "  const db = await getDB();",
    "  const keys = Object.keys(data).map(k => `${k} = ?`).join(', ');",
    "  const vals = Object.values(data);",
    "  await db.runAsync(`UPDATE profile SET ${keys} WHERE id = 1`, vals);",
    "}",
    "",
    "// ── TRANSACTIONS ─────────────────────────────────────────────────",
    "export async function getTxnsThisMonth() {",
    "  const db = await getDB();",
    "  const from = format(startOfMonth(new Date()), 'yyyy-MM-dd');",
    "  const to   = format(endOfMonth(new Date()),   'yyyy-MM-dd');",
    "  return db.getAllAsync<Transaction>(",
    "    `SELECT * FROM transactions",
    "     WHERE date(txn_date) BETWEEN ? AND ?",
    "     ORDER BY txn_date DESC`,",
    "    [from, to]",
    "  );",
    "}",
    "",
    "export async function getTxnsLast48h() {",
    "  const db = await getDB();",
    "  return db.getAllAsync<Transaction>(",
    "    `SELECT * FROM transactions",
    "     WHERE type = 'debit'",
    "     AND txn_date >= datetime('now', '-48 hours')",
    "     ORDER BY txn_date DESC`",
    "  );",
    "}",
    "",
    "export async function getCategoryTotals() {",
    "  const db = await getDB();",
    "  const from = format(startOfMonth(new Date()), 'yyyy-MM-dd');",
    "  return db.getAllAsync<{category: string; total: number; count: number}>(",
    "    `SELECT category, SUM(amount) as total, COUNT(*) as count",
    "     FROM transactions",
    "     WHERE type = 'debit' AND date(txn_date) >= ?",
    "     GROUP BY category ORDER BY total DESC`,",
    "    [from]",
    "  );",
    "}",
    "",
    "export async function addTransaction(t: Omit<Transaction,'id'|'created_at'>) {",
    "  const db = await getDB();",
    "  return db.runAsync(",
    "    `INSERT INTO transactions (amount,type,category,merchant,note,txn_date,member_id)",
    "     VALUES (?,?,?,?,?,?,?)`,",
    "    [t.amount, t.type, t.category, t.merchant ?? '',",
    "     t.note ?? '', t.txn_date, t.member_id ?? 0]",
    "  );",
    "}",
    "",
    "export async function deleteTransaction(id: number) {",
    "  const db = await getDB();",
    "  await db.runAsync('DELETE FROM transactions WHERE id = ?', [id]);",
    "}",
    "",
    "// ── BILLS ────────────────────────────────────────────────────────",
    "export async function getBills() {",
    "  const db = await getDB();",
    "  return db.getAllAsync<Bill>(",
    "    'SELECT * FROM bills WHERE active = 1 ORDER BY due_day'",
    "  );",
    "}",
    "",
    "export async function addBill(b: Omit<Bill,'id'>) {",
    "  const db = await getDB();",
    "  return db.runAsync(",
    "    'INSERT INTO bills (name,amount,category,due_day,color) VALUES (?,?,?,?,?)',",
    "    [b.name, b.amount, b.category, b.due_day, b.color ?? '#EF4444']",
    "  );",
    "}",
    "",
    "export async function deleteBill(id: number) {",
    "  const db = await getDB();",
    "  await db.runAsync('UPDATE bills SET active = 0 WHERE id = ?', [id]);",
    "}",
    "",
    "// ── INVOICES ─────────────────────────────────────────────────────",
    "export async function getInvoices() {",
    "  const db = await getDB();",
    "  return db.getAllAsync<Invoice>(",
    "    'SELECT * FROM invoices ORDER BY due_date ASC'",
    "  );",
    "}",
    "",
    "export async function addInvoice(inv: Omit<Invoice,'id'>) {",
    "  const db = await getDB();",
    "  return db.runAsync(",
    "    'INSERT INTO invoices (client,project,amount,due_date) VALUES (?,?,?,?)',",
    "    [inv.client, inv.project, inv.amount, inv.due_date]",
    "  );",
    "}",
    "",
    "export async function updateInvoiceStatus(id: number, status: string) {",
    "  const db = await getDB();",
    "  await db.runAsync('UPDATE invoices SET status = ? WHERE id = ?', [status, id]);",
    "}",
    "",
    "// ── MEMBERS ──────────────────────────────────────────────────────",
    "export async function getMembers() {",
    "  const db = await getDB();",
    "  return db.getAllAsync<Member>('SELECT * FROM members ORDER BY id');",
    "}",
    "",
    "// ── JARS ─────────────────────────────────────────────────────────",
    "export async function getJars() {",
    "  const db = await getDB();",
    "  return db.getAllAsync<Jar>('SELECT * FROM jars ORDER BY id');",
    "}",
    "",
    "export async function addToJar(id: number, amount: number) {",
    "  const db = await getDB();",
    "  await db.runAsync(",
    "    'UPDATE jars SET saved = MIN(target, saved + ?) WHERE id = ?',",
    "    [amount, id]",
    "  );",
    "}",
    "",
    "// ── COACH CHAT ───────────────────────────────────────────────────",
    "export async function getChatHistory() {",
    "  const db = await getDB();",
    "  return db.getAllAsync<ChatMessage>(",
    "    'SELECT * FROM coach_chat ORDER BY created_at ASC LIMIT 50'",
    "  );",
    "}",
    "",
    "export async function saveChatMessage(role: string, content: string) {",
    "  const db = await getDB();",
    "  await db.runAsync(",
    "    'INSERT INTO coach_chat (role, content) VALUES (?, ?)',",
    "    [role, content]",
    "  );",
    "}",
    "",
    "// ── TYPES ────────────────────────────────────────────────────────",
    "export interface Profile {",
    "  id: number; name: string; city: string;",
    "  income_type: string; monthly_income: number;",
    "  salary_day: number; current_balance: number;",
    "  safety_pct: number; claude_key: string;",
    "}",
    "export interface Transaction {",
    "  id: number; amount: number; type: string;",
    "  category: string; merchant: string; note: string;",
    "  txn_date: string; is_recurring: number;",
    "  member_id: number; created_at: string;",
    "}",
    "export interface Bill {",
    "  id: number; name: string; amount: number;",
    "  category: string; due_day: number; active: number; color: string;",
    "}",
    "export interface Invoice {",
    "  id: number; client: string; project: string;",
    "  amount: number; status: string; due_date: string; raised_date: string;",
    "}",
    "export interface Member {",
    "  id: number; name: string; initials: string;",
    "  monthly_limit: number; color: string;",
    "}",
    "export interface Jar {",
    "  id: number; name: string; target: number;",
    "  saved: number; color: string; icon: string; auto_save: number;",
    "}",
    "export interface ChatMessage {",
    "  id: number; role: string; content: string; created_at: string;",
    "}",
  ]),
  sp(), pgBreak(),
];

// ─── ENGINES ─────────────────────────────────────────────────────────────────
const s5 = [
  h1("File 5 — engine/  (The Financial Brain — All 3 Engines)"),
  hr(C.acc, 4), sp(),

  h2("5a — engine/safeToSpend.ts"),
  fileTag("engine/safeToSpend.ts"),
  ...code([
    "import { getBills, getTxnsThisMonth } from '../db/queries';",
    "import { Profile } from '../db/queries';",
    "",
    "export interface STSResult {",
    "  safeAmount:       number;  // ← THE NUMBER shown on home screen",
    "  currentBalance:   number;",
    "  reservedForBills: number;  // bills still due this cycle",
    "  spentSoFar:       number;  // debits this month",
    "  safetyBuffer:     number;  // 5% of income",
    "  percentUsed:      number;  // 0–100, for progress bar",
    "  dailyBudget:      number;  // safe / days remaining",
    "  daysLeft:         number;",
    "}",
    "",
    "export async function calcSTS(profile: Profile): Promise<STSResult> {",
    "  const today = new Date();",
    "  const dayOfMonth  = today.getDate();",
    "  const daysInMonth = new Date(",
    "    today.getFullYear(), today.getMonth() + 1, 0).getDate();",
    "  const daysLeft = Math.max(1, daysInMonth - dayOfMonth);",
    "",
    "  // Bills still due AFTER today in this cycle",
    "  const bills = await getBills();",
    "  const reservedForBills = bills",
    "    .filter(b => b.due_day > dayOfMonth)",
    "    .reduce((s, b) => s + b.amount, 0);",
    "",
    "  // What was already spent this month (debits only)",
    "  const txns = await getTxnsThisMonth();",
    "  const spentSoFar = txns",
    "    .filter(t => t.type === 'debit')",
    "    .reduce((s, t) => s + t.amount, 0);",
    "",
    "  // Safety buffer — minimum ₹2,000 or 5% of income",
    "  const safetyBuffer = Math.max(",
    "    2000,",
    "    profile.monthly_income * (profile.safety_pct / 100)",
    "  );",
    "",
    "  // Core formula",
    "  const safeAmount = Math.max(0,",
    "    profile.current_balance - reservedForBills - safetyBuffer",
    "  );",
    "",
    "  // Progress: how much of the 'spendable pool' is used",
    "  const spendablePool = Math.max(1,",
    "    profile.monthly_income - reservedForBills - safetyBuffer",
    "  );",
    "  const percentUsed = Math.min(100,",
    "    (spentSoFar / spendablePool) * 100",
    "  );",
    "",
    "  return {",
    "    safeAmount:       Math.round(safeAmount),",
    "    currentBalance:   Math.round(profile.current_balance),",
    "    reservedForBills: Math.round(reservedForBills),",
    "    spentSoFar:       Math.round(spentSoFar),",
    "    safetyBuffer:     Math.round(safetyBuffer),",
    "    percentUsed:      Math.round(percentUsed),",
    "    dailyBudget:      Math.round(safeAmount / daysLeft),",
    "    daysLeft,",
    "  };",
    "}",
  ]),

  sp(),
  h2("5b — engine/dangerWindow.ts"),
  fileTag("engine/dangerWindow.ts"),
  ...code([
    "import { getBills, getCategoryTotals } from '../db/queries';",
    "import { Profile } from '../db/queries';",
    "import { addDays, format, getDate } from 'date-fns';",
    "",
    "export interface DayForecast {",
    "  day:        number;",
    "  date:       string;",
    "  balance:    number;",
    "  events:     string[];",
    "  riskLevel:  'safe' | 'warning' | 'danger';",
    "}",
    "",
    "export interface DangerSummary {",
    "  hasDanger:   boolean;",
    "  firstDay:    number | null;",
    "  firstDate:   string | null;",
    "  shortfall:   number;",
    "  forecasts:   DayForecast[];",
    "}",
    "",
    "export async function buildDangerWindow(",
    "  profile: Profile",
    "): Promise<DangerSummary> {",
    "  const bills    = await getBills();",
    "  const catTotals = await getCategoryTotals();",
    "",
    "  // Daily variable burn = this month's variable spend / days so far",
    "  const variableSpend = catTotals",
    "    .filter(c => !['rent','emi','subscription'].includes(c.category))",
    "    .reduce((s, c) => s + c.total, 0);",
    "  const dayOfMonth = new Date().getDate();",
    "  const dailyBurn  = variableSpend / Math.max(1, dayOfMonth);",
    "",
    "  let runningBalance = profile.current_balance;",
    "  const forecasts: DayForecast[] = [];",
    "  const today = new Date();",
    "",
    "  for (let i = 1; i <= 30; i++) {",
    "    const futureDate = addDays(today, i);",
    "    const dom        = getDate(futureDate);",
    "    const events: string[] = [];",
    "",
    "    // Deduct bills due on this day",
    "    bills.forEach(b => {",
    "      if (b.due_day === dom) {",
    "        runningBalance -= b.amount;",
    "        events.push(`${b.name}: -₹${b.amount.toLocaleString('en-IN')}`);",
    "      }",
    "    });",
    "",
    "    // Add salary/income on salary day",
    "    if (dom === profile.salary_day) {",
    "      runningBalance += profile.monthly_income;",
    "      events.push(`Income: +₹${profile.monthly_income.toLocaleString('en-IN')}`);",
    "    }",
    "",
    "    // Daily variable burn",
    "    runningBalance -= dailyBurn;",
    "",
    "    const riskLevel: DayForecast['riskLevel'] =",
    "      runningBalance < 0     ? 'danger'  :",
    "      runningBalance < 5000  ? 'warning' : 'safe';",
    "",
    "    forecasts.push({",
    "      day: i,",
    "      date: format(futureDate, 'MMM d'),",
    "      balance: Math.round(runningBalance),",
    "      events,",
    "      riskLevel,",
    "    });",
    "  }",
    "",
    "  const firstDanger = forecasts.find(f => f.riskLevel === 'danger');",
    "",
    "  return {",
    "    hasDanger:  !!firstDanger,",
    "    firstDay:   firstDanger?.day ?? null,",
    "    firstDate:  firstDanger?.date ?? null,",
    "    shortfall:  firstDanger ? Math.abs(Math.min(0, firstDanger.balance)) : 0,",
    "    forecasts,",
    "  };",
    "}",
  ]),

  sp(),
  h2("5c — engine/doomDetector.ts"),
  fileTag("engine/doomDetector.ts"),
  ...code([
    "import { getTxnsLast48h } from '../db/queries';",
    "",
    "export interface DoomResult {",
    "  isDoom:      boolean;",
    "  count:       number;",
    "  total:       number;",
    "  merchants:   string[];",
    "  severity:    'none' | 'mild' | 'high';",
    "}",
    "",
    "export async function detectDoom(): Promise<DoomResult> {",
    "  const txns = await getTxnsLast48h();",
    "",
    "  // Filter micro-transactions (under ₹800)",
    "  const micro = txns.filter(t => t.amount < 800);",
    "",
    "  const total     = micro.reduce((s, t) => s + t.amount, 0);",
    "  const merchants = [...new Set(micro.map(t => t.merchant).filter(Boolean))];",
    "",
    "  const isDoom   = micro.length >= 4;",
    "  const severity =",
    "    micro.length >= 7 ? 'high' :",
    "    micro.length >= 4 ? 'mild' : 'none';",
    "",
    "  return {",
    "    isDoom,",
    "    count:     micro.length,",
    "    total:     Math.round(total),",
    "    merchants: merchants.slice(0, 5),",
    "    severity,",
    "  };",
    "}",
  ]),
  sp(), pgBreak(),
];

// ─── ZUSTAND STORE ────────────────────────────────────────────────────────────
const s6 = [
  h1("File 6 — store/useStore.ts  (Global State)"),
  hr(C.acc, 4), sp(),
  body("Zustand holds the live financial state. Every screen subscribes to this. When you add a transaction, balance updates here and ALL screens instantly re-render with real numbers."),
  sp(),
  fileTag("store/useStore.ts"),
  ...code([
    "import { create } from 'zustand';",
    "import { STSResult, calcSTS } from '../engine/safeToSpend';",
    "import { DangerSummary, buildDangerWindow } from '../engine/dangerWindow';",
    "import { DoomResult, detectDoom } from '../engine/doomDetector';",
    "import { getProfile, updateProfile, Profile } from '../db/queries';",
    "",
    "interface AppState {",
    "  // Profile",
    "  profile:      Profile | null;",
    "  setProfile:   (p: Profile) => void;",
    "  refreshProfile: () => Promise<void>;",
    "",
    "  // Computed financial state",
    "  sts:          STSResult | null;",
    "  danger:       DangerSummary | null;",
    "  doom:         DoomResult | null;",
    "  isLoading:    boolean;",
    "",
    "  // Actions",
    "  refreshAll:   () => Promise<void>;",
    "  updateBalance:(amount: number, type: 'add'|'subtract') => Promise<void>;",
    "}",
    "",
    "export const useStore = create<AppState>((set, get) => ({",
    "  profile:   null,",
    "  sts:       null,",
    "  danger:    null,",
    "  doom:      null,",
    "  isLoading: true,",
    "",
    "  setProfile: (p) => set({ profile: p }),",
    "",
    "  refreshProfile: async () => {",
    "    const p = await getProfile();",
    "    if (p) set({ profile: p });",
    "  },",
    "",
    "  refreshAll: async () => {",
    "    set({ isLoading: true });",
    "    try {",
    "      const profile = await getProfile();",
    "      if (!profile) { set({ isLoading: false }); return; }",
    "",
    "      // Run all 3 engines in parallel",
    "      const [sts, danger, doom] = await Promise.all([",
    "        calcSTS(profile),",
    "        buildDangerWindow(profile),",
    "        detectDoom(),",
    "      ]);",
    "",
    "      set({ profile, sts, danger, doom, isLoading: false });",
    "    } catch (e) {",
    "      console.error('Store refresh error:', e);",
    "      set({ isLoading: false });",
    "    }",
    "  },",
    "",
    "  // Called after adding any transaction to keep balance in sync",
    "  updateBalance: async (amount, type) => {",
    "    const { profile } = get();",
    "    if (!profile) return;",
    "    const newBalance = type === 'add'",
    "      ? profile.current_balance + amount",
    "      : profile.current_balance - amount;",
    "    await updateProfile({ current_balance: Math.max(0, newBalance) });",
    "    await get().refreshAll();",
    "  },",
    "}));",
  ]),
  sp(), pgBreak(),
];

// ─── APP.TSX ──────────────────────────────────────────────────────────────────
const s7 = [
  h1("File 7 — App.tsx  (Entry Point + Navigation)"),
  hr(C.acc, 4), sp(),
  body("The complete App.tsx. This handles font loading, DB init, the loading gate, and the full navigation tree. Replace your current App.tsx entirely."),
  sp(),
  fileTag("App.tsx"),
  ...code([
    "import React, { useEffect, useState } from 'react';",
    "import { View, ActivityIndicator, StatusBar } from 'react-native';",
    "import { NavigationContainer } from '@react-navigation/native';",
    "import { createBottomTabNavigator } from '@react-navigation/bottom-tabs';",
    "import { createStackNavigator } from '@react-navigation/stack';",
    "import { GestureHandlerRootView } from 'react-native-gesture-handler';",
    "import { SafeAreaProvider } from 'react-native-safe-area-context';",
    "import { Ionicons } from '@expo/vector-icons';",
    "import {",
    "  useFonts,",
    "  DMSans_400Regular,",
    "  DMSans_500Medium,",
    "} from '@expo-google-fonts/dm-sans';",
    "import {",
    "  SpaceGrotesk_600SemiBold,",
    "  SpaceGrotesk_700Bold,",
    "} from '@expo-google-fonts/space-grotesk';",
    "",
    "import { initDB } from './db/schema';",
    "import { useStore } from './store/useStore';",
    "import { colors } from './theme';",
    "",
    "// Screens",
    "import HomeScreen     from './app/home';",
    "import ForecastScreen from './app/forecast';",
    "import GigScreen      from './app/gig';",
    "import FamilyScreen   from './app/family';",
    "import SettingsScreen from './app/settings';",
    "",
    "// Stack screens (modals)",
    "import AlertsScreen  from './app/alerts';",
    "import DoomScreen    from './app/doom';",
    "import BreatheScreen from './app/breathe';",
    "import JugaadScreen  from './app/jugaad';",
    "import CoachScreen   from './app/coach';",
    "import SchemesScreen from './app/schemes';",
    "import AddTxnScreen  from './app/addTransaction';",
    "import OnboardScreen from './app/onboard';",
    "",
    "const Tab   = createBottomTabNavigator();",
    "const Stack = createStackNavigator();",
    "",
    "function TabNavigator() {",
    "  return (",
    "    <Tab.Navigator",
    "      screenOptions={({ route }) => ({",
    "        headerShown: false,",
    "        tabBarStyle: {",
    "          backgroundColor: colors.s1,",
    "          borderTopColor:  colors.border,",
    "          borderTopWidth:  1,",
    "          height:          64,",
    "          paddingBottom:   10,",
    "          paddingTop:      6,",
    "        },",
    "        tabBarActiveTintColor:   colors.accent,",
    "        tabBarInactiveTintColor: colors.muted,",
    "        tabBarLabelStyle: { fontSize: 11, fontFamily: 'DMSans_500Medium' },",
    "        tabBarIcon: ({ color, size }) => {",
    "          const icons: Record<string, string> = {",
    "            Home:     'home-outline',",
    "            Forecast: 'stats-chart-outline',",
    "            Gig:      'briefcase-outline',",
    "            Family:   'people-outline',",
    "            Settings: 'settings-outline',",
    "          };",
    "          return <Ionicons name={icons[route.name] as any} size={22} color={color} />;",
    "        },",
    "      })}",
    "    >",
    "      <Tab.Screen name='Home'     component={HomeScreen} />",
    "      <Tab.Screen name='Forecast' component={ForecastScreen} />",
    "      <Tab.Screen name='Gig'      component={GigScreen} />",
    "      <Tab.Screen name='Family'   component={FamilyScreen} />",
    "      <Tab.Screen name='Settings' component={SettingsScreen} />",
    "    </Tab.Navigator>",
    "  );",
    "}",
    "",
    "export default function App() {",
    "  const [dbReady, setDbReady]   = useState(false);",
    "  const refreshAll = useStore(s => s.refreshAll);",
    "",
    "  const [fontsLoaded] = useFonts({",
    "    DMSans_400Regular,",
    "    DMSans_500Medium,",
    "    SpaceGrotesk_600SemiBold,",
    "    SpaceGrotesk_700Bold,",
    "  });",
    "",
    "  useEffect(() => {",
    "    async function boot() {",
    "      await initDB();          // create tables",
    "      await refreshAll();      // run all 3 engines",
    "      setDbReady(true);",
    "    }",
    "    boot();",
    "  }, []);",
    "",
    "  // Show nothing until fonts + DB are both ready",
    "  if (!fontsLoaded || !dbReady) {",
    "    return (",
    "      <View style={{ flex:1, backgroundColor: colors.bg,",
    "        justifyContent:'center', alignItems:'center' }}>",
    "        <ActivityIndicator size='large' color={colors.accent} />",
    "      </View>",
    "    );",
    "  }",
    "",
    "  return (",
    "    <GestureHandlerRootView style={{ flex: 1 }}>",
    "      <SafeAreaProvider>",
    "        <StatusBar barStyle='light-content' backgroundColor={colors.bg} />",
    "        <NavigationContainer>",
    "          <Stack.Navigator",
    "            screenOptions={{",
    "              headerShown: false,",
    "              cardStyle: { backgroundColor: colors.bg },",
    "            }}",
    "          >",
    "            <Stack.Screen name='Tabs'     component={TabNavigator} />",
    "            <Stack.Screen name='Onboard'  component={OnboardScreen}",
    "              options={{ presentation: 'modal' }} />",
    "            <Stack.Screen name='Alerts'   component={AlertsScreen}",
    "              options={{ presentation: 'modal' }} />",
    "            <Stack.Screen name='Doom'     component={DoomScreen}",
    "              options={{ presentation: 'modal' }} />",
    "            <Stack.Screen name='Breathe'  component={BreatheScreen}",
    "              options={{ presentation: 'modal' }} />",
    "            <Stack.Screen name='Jugaad'   component={JugaadScreen}",
    "              options={{ presentation: 'modal' }} />",
    "            <Stack.Screen name='Coach'    component={CoachScreen}",
    "              options={{ presentation: 'modal' }} />",
    "            <Stack.Screen name='Schemes'  component={SchemesScreen}",
    "              options={{ presentation: 'modal' }} />",
    "            <Stack.Screen name='AddTxn'   component={AddTxnScreen}",
    "              options={{ presentation: 'modal' }} />",
    "          </Stack.Navigator>",
    "        </NavigationContainer>",
    "      </SafeAreaProvider>",
    "    </GestureHandlerRootView>",
    "  );",
    "}",
  ]),
  sp(), pgBreak(),
];

// ─── HOME SCREEN ──────────────────────────────────────────────────────────────
const s8 = [
  h1("File 8 — app/home.tsx  (Complete Home Screen)"),
  hr(C.acc, 4), sp(),
  body("The Home screen reads LIVE from the Zustand store. Every number updates in real-time. Includes the pulse animation, danger window bar, doom banner, and UPI category grid — all wired to real data."),
  sp(),
  fileTag("app/home.tsx"),
  ...code([
    "import React, { useEffect, useCallback } from 'react';",
    "import {",
    "  View, Text, ScrollView, TouchableOpacity,",
    "  StyleSheet, Animated, RefreshControl,",
    "} from 'react-native';",
    "import { useFocusEffect, useNavigation } from '@react-navigation/native';",
    "import { SafeAreaView } from 'react-native-safe-area-context';",
    "import { Ionicons } from '@expo/vector-icons';",
    "import { useStore } from '../store/useStore';",
    "import { getCategoryTotals } from '../db/queries';",
    "import { colors, card, type, spacing, radius } from '../theme';",
    "",
    "export default function HomeScreen() {",
    "  const { sts, danger, doom, isLoading, refreshAll, profile } =",
    "    useStore();",
    "  const nav = useNavigation<any>();",
    "  const [cats, setCats] = React.useState<any[]>([]);",
    "  const pulseAnim = React.useRef(new Animated.Value(1)).current;",
    "",
    "  // Refresh every time user comes back to this tab",
    "  useFocusEffect(useCallback(() => { refreshAll(); }, []));",
    "",
    "  useEffect(() => {",
    "    getCategoryTotals().then(setCats);",
    "  }, [sts]);  // re-fetch when sts changes (= after new txn)",
    "",
    "  // Pulse animation for the live dot",
    "  useEffect(() => {",
    "    Animated.loop(Animated.sequence([",
    "      Animated.timing(pulseAnim, { toValue: 1.5, duration: 900,  useNativeDriver: true }),",
    "      Animated.timing(pulseAnim, { toValue: 1,   duration: 900,  useNativeDriver: true }),",
    "    ])).start();",
    "  }, []);",
    "",
    "  // Determine safe-to-spend color",
    "  const stsColor =",
    "    !sts              ? colors.muted :",
    "    sts.safeAmount < 1000  ? colors.red   :",
    "    sts.safeAmount < 5000  ? colors.accent2 :",
    "    colors.green;",
    "",
    "  const fmt = (n: number) => '₹' + Math.abs(n).toLocaleString('en-IN');",
    "",
    "  return (",
    "    <SafeAreaView style={s.root}>",
    "      {/* ── TOP BAR ── */}",
    "      <View style={s.topbar}>",
    "        <View>",
    "          <Text style={type.label}>Good morning</Text>",
    "          <Text style={[type.h2, { marginTop: 2 }]}>",
    "            {profile?.name ?? 'You'} 👋",
    "          </Text>",
    "        </View>",
    "        <TouchableOpacity",
    "          style={s.alertBtn}",
    "          onPress={() => nav.navigate('Alerts')}",
    "        >",
    "          <Ionicons name='notifications-outline' size={22} color={colors.muted} />",
    "          {danger?.hasDanger && <View style={s.alertDot} />}",
    "        </TouchableOpacity>",
    "      </View>",
    "",
    "      <ScrollView",
    "        showsVerticalScrollIndicator={false}",
    "        contentContainerStyle={s.scroll}",
    "        refreshControl={",
    "          <RefreshControl",
    "            refreshing={isLoading}",
    "            onRefresh={refreshAll}",
    "            tintColor={colors.accent}",
    "          />",
    "        }",
    "      >",
    "        {/* ── SAFE TO SPEND HERO ── */}",
    "        <View style={[card.base, s.heroCard]}>",
    "          <View style={s.heroTop}>",
    "            <View style={s.pulseWrap}>",
    "              <View style={[s.pulseDot, { backgroundColor: stsColor }]} />",
    "              <Animated.View style={[s.pulseRing,",
    "                { borderColor: stsColor, transform: [{ scale: pulseAnim }] }",
    "              ]} />",
    "            </View>",
    "            <Text style={type.label}>Safe to spend today</Text>",
    "          </View>",
    "          <Text style={[type.hero, { color: stsColor }]}>",
    "            {sts ? fmt(sts.safeAmount) : '…'}",
    "          </Text>",
    "          <Text style={[type.body, { marginTop: 4 }]}>",
    "            All upcoming bills pre-reserved · ₹{sts?.dailyBudget ?? 0}/day",
    "          </Text>",
    "",
    "          {/* Progress bar */}",
    "          <View style={s.barBg}>",
    "            <View style={[s.barFill, {",
    "              width: `${sts?.percentUsed ?? 0}%`,",
    "              backgroundColor: stsColor",
    "            }]} />",
    "          </View>",
    "",
    "          {/* Breakdown row */}",
    "          <View style={s.breakRow}>",
    "            {[",
    "              ['Income',   fmt(profile?.monthly_income ?? 0), colors.text],",
    "              ['Reserved', fmt(sts?.reservedForBills ?? 0),   colors.accent2],",
    "              ['Spent',    fmt(sts?.spentSoFar ?? 0),         colors.red],",
    "            ].map(([k, v, c]) => (",
    "              <View key={k as string} style={{ alignItems: 'center' }}>",
    "                <Text style={type.label}>{k}</Text>",
    "                <Text style={[type.bodyMd, { color: c as string }]}>{v}</Text>",
    "              </View>",
    "            ))}",
    "          </View>",
    "        </View>",
    "",
    "        {/* ── DANGER WINDOW + JUGAAD ROW ── */}",
    "        <View style={s.row2}>",
    "          {/* Danger Window mini card */}",
    "          <TouchableOpacity",
    "            style={[card.base, s.halfCard,",
    "              danger?.hasDanger ? card.danger : {}]}",
    "            onPress={() => nav.navigate('Forecast')}",
    "          >",
    "            <Text style={type.label}>Danger window</Text>",
    "            <View style={s.dwBar}>",
    "              {/* Simplified 30-block timeline bar */}",
    "              {Array.from({ length: 30 }, (_, i) => {",
    "                const seg = danger?.forecasts[i];",
    "                const col =",
    "                  seg?.riskLevel === 'danger'  ? colors.red    :",
    "                  seg?.riskLevel === 'warning' ? colors.accent2 :",
    "                  colors.green + '44';",
    "                return <View key={i} style={[s.dwTick, { backgroundColor: col }]} />;",
    "              })}",
    "            </View>",
    "            {danger?.hasDanger ? (",
    "              <Text style={[type.body, { color: colors.red, marginTop: 6 }]}>",
    "                ⚡ Day {danger.firstDay} · -{fmt(danger.shortfall)}",
    "              </Text>",
    "            ) : (",
    "              <Text style={[type.body, { color: colors.green, marginTop: 6 }]}>",
    "                ✓ All clear this month",
    "              </Text>",
    "            )}",
    "          </TouchableOpacity>",
    "",
    "          {/* Jugaad Score mini card */}",
    "          <TouchableOpacity",
    "            style={[card.base, s.halfCard,",
    "              { borderColor: colors.purple + '55' }]}",
    "            onPress={() => nav.navigate('Jugaad')}",
    "          >",
    "            <Text style={type.label}>Jugaad score</Text>",
    "            <Text style={[type.big, { color: colors.purple }]}>74",
    "              <Text style={[type.body, { color: colors.muted }]}>/100</Text>",
    "            </Text>",
    "            <Text style={[type.body, { color: colors.purple, marginTop: 6 }]}>",
    "              2 new tips →",
    "            </Text>",
    "          </TouchableOpacity>",
    "        </View>",
    "",
    "        {/* ── DOOM BANNER (only shown when detected) ── */}",
    "        {doom?.isDoom && (",
    "          <TouchableOpacity",
    "            style={card.danger}",
    "            onPress={() => nav.navigate('Doom')}",
    "          >",
    "            <View style={s.doomRow}>",
    "              <Text style={{ fontSize: 28 }}>🌀</Text>",
    "              <View style={{ flex: 1, marginLeft: 12 }}>",
    "                <Text style={[type.h3, { color: '#FCA5A5' }]}>",
    "                  Doom spending detected",
    "                </Text>",
    "                <Text style={type.body}>",
    "                  {doom.count} purchases in 48hrs · {fmt(doom.total)}",
    "                </Text>",
    "              </View>",
    "              <Ionicons name='chevron-forward' size={18} color={colors.red} />",
    "            </View>",
    "          </TouchableOpacity>",
    "        )}",
    "",
    "        {/* ── UPI CATEGORIES ── */}",
    "        <Text style={[type.h3, s.sectionHead]}>Spending this month</Text>",
    "        <View style={card.base}>",
    "          {cats.length === 0 ? (",
    "            <Text style={[type.body, { textAlign: 'center', padding: 16 }]}>",
    "              No transactions yet. Add your first one →",
    "            </Text>",
    "          ) : (",
    "            cats.map((cat, i) => (",
    "              <View key={cat.category}",
    "                style={[s.catRow, i > 0 && s.catBorder]}",
    "              >",
    "                <Text style={{ fontSize: 22 }}>",
    "                  {catIcon(cat.category)}",
    "                </Text>",
    "                <View style={{ flex: 1, marginLeft: 12 }}>",
    "                  <Text style={type.bodyMd}>{cat.category}</Text>",
    "                  <Text style={type.body}>{cat.count} transactions</Text>",
    "                </View>",
    "                <Text style={[type.num, { color: colors.accent2 }]}>",
    "                  {fmt(cat.total)}",
    "                </Text>",
    "              </View>",
    "            ))",
    "          )}",
    "        </View>",
    "",
    "        {/* ── ADD TRANSACTION FAB ── */}",
    "        <TouchableOpacity",
    "          style={s.fab}",
    "          onPress={() => nav.navigate('AddTxn')}",
    "        >",
    "          <Ionicons name='add' size={28} color='#fff' />",
    "        </TouchableOpacity>",
    "      </ScrollView>",
    "    </SafeAreaView>",
    "  );",
    "}",
    "",
    "function catIcon(cat: string) {",
    "  const map: Record<string,string> = {",
    "    food: '🍕', groceries: '🛒', transport: '🚗', rent: '🏠',",
    "    emi: '💳', subscription: '📱', medical: '🏥', entertainment: '🎮',",
    "    other: '💰',",
    "  };",
    "  return map[cat] ?? '💸';",
    "}",
    "",
    "const s = StyleSheet.create({",
    "  root:      { flex: 1, backgroundColor: colors.bg },",
    "  topbar:    { flexDirection:'row', justifyContent:'space-between',",
    "               alignItems:'center', paddingHorizontal:16, paddingTop:8, paddingBottom:4 },",
    "  alertBtn:  { width:40, height:40, borderRadius:20,",
    "               backgroundColor:colors.s2, justifyContent:'center', alignItems:'center' },",
    "  alertDot:  { position:'absolute', top:8, right:8, width:8, height:8,",
    "               borderRadius:4, backgroundColor:colors.red },",
    "  scroll:    { padding:16, paddingBottom:100 },",
    "  heroCard:  { position:'relative' },",
    "  heroTop:   { flexDirection:'row', alignItems:'center', gap:8, marginBottom:8 },",
    "  pulseWrap: { width:16, height:16, justifyContent:'center', alignItems:'center' },",
    "  pulseDot:  { width:10, height:10, borderRadius:5, position:'absolute' },",
    "  pulseRing: { width:16, height:16, borderRadius:8, borderWidth:2, position:'absolute' },",
    "  barBg:     { height:6, backgroundColor:colors.s3, borderRadius:3,",
    "               marginTop:12, overflow:'hidden' },",
    "  barFill:   { height:'100%', borderRadius:3 },",
    "  breakRow:  { flexDirection:'row', justifyContent:'space-between', marginTop:10 },",
    "  row2:      { flexDirection:'row', gap:12, marginBottom:12 },",
    "  halfCard:  { flex:1, marginBottom:0 },",
    "  dwBar:     { flexDirection:'row', gap:1.5, marginTop:8, height:12 },",
    "  dwTick:    { flex:1, borderRadius:1 },",
    "  doomRow:   { flexDirection:'row', alignItems:'center' },",
    "  sectionHead:{ marginBottom:10, marginTop:4 },",
    "  catRow:    { flexDirection:'row', alignItems:'center', paddingVertical:12 },",
    "  catBorder: { borderTopWidth:1, borderTopColor:colors.border },",
    "  fab:       { position:'absolute', bottom:24, right:0,",
    "               width:56, height:56, borderRadius:28,",
    "               backgroundColor:colors.accent,",
    "               justifyContent:'center', alignItems:'center',",
    "               shadowColor:'#FF6B35', shadowOffset:{width:0,height:4},",
    "               shadowOpacity:0.5, shadowRadius:12, elevation:10 },",
    "});",
  ]),
  sp(), pgBreak(),
];

// ─── AI CLAUDE ────────────────────────────────────────────────────────────────
const s9 = [
  h1("File 9 — ai/claude.ts  (Complete AI Integration)"),
  hr(C.acc, 4), sp(),
  body("Handles all Claude API calls. Uses claude-haiku-4-5 for speed and cost. Includes a mock fallback so the app still works if you haven't added your API key yet."),
  sp(),
  fileTag("ai/claude.ts"),
  ...code([
    "import { getProfile } from '../db/queries';",
    "",
    "const API_URL = 'https://api.anthropic.com/v1/messages';",
    "",
    "async function callClaude(",
    "  messages: { role: string; content: string }[],",
    "  system: string,",
    "  maxTokens = 500",
    "): Promise<string> {",
    "  const profile = await getProfile();",
    "  const key = profile?.claude_key ?? '';",
    "",
    "  if (!key) {",
    "    return '[Add your Claude API key in Settings to enable AI features]';",
    "  }",
    "",
    "  try {",
    "    const res = await fetch(API_URL, {",
    "      method: 'POST',",
    "      headers: {",
    "        'Content-Type':      'application/json',",
    "        'x-api-key':         key,",
    "        'anthropic-version': '2023-06-01',",
    "      },",
    "      body: JSON.stringify({",
    "        model:      'claude-haiku-4-5',",
    "        max_tokens: maxTokens,",
    "        system,",
    "        messages,",
    "      }),",
    "    });",
    "",
    "    if (!res.ok) {",
    "      const err = await res.text();",
    "      throw new Error(`Claude API error: ${err}`);",
    "    }",
    "",
    "    const data = await res.json();",
    "    return data.content?.[0]?.text ?? 'No response';",
    "  } catch (e: any) {",
    "    console.error('Claude error:', e.message);",
    "    return 'AI temporarily unavailable. Please try again.';",
    "  }",
    "}",
    "",
    "// ── AI COACH ─────────────────────────────────────────────────────",
    "const COACH_SYSTEM = `You are Artha's financial coach.",
    "You are warm, calm, and non-judgmental.",
    "RULES:",
    "- Never say 'you should have', 'bad decision', or 'mistake'",
    "- Only discuss what is possible from RIGHT NOW forward",
    "- If user seems anxious, acknowledge feelings FIRST",
    "- Keep responses under 100 words (this is a mobile app)",
    "- You are NOT a SEBI advisor — never give specific stock picks",
    "- Speak in plain English — no jargon`;",
    "",
    "export async function coachChat(",
    "  messages: { role: string; content: string }[],",
    "  financialContext: {",
    "    safeToSpend:  number;",
    "    dangerDay?:   number;",
    "    spentSoFar:   number;",
    "    topCategory?: string;",
    "  }",
    ") {",
    "  const ctxPrefix = `",
    "[User's current financial snapshot:",
    "Safe to spend: ₹${financialContext.safeToSpend}",
    "Spent this month: ₹${financialContext.spentSoFar}",
    "${financialContext.dangerDay ? `Danger window: Day ${financialContext.dangerDay}` : 'No danger window'}",
    "Top category: ${financialContext.topCategory ?? 'Unknown'}]",
    "`;",
    "",
    "  const augmented = [",
    "    { role: 'user', content: ctxPrefix },",
    "    ...messages,",
    "  ];",
    "",
    "  return callClaude(augmented, COACH_SYSTEM, 400);",
    "}",
    "",
    "// ── JUGAAD TIPS ──────────────────────────────────────────────────",
    "export async function getJugaadTips(context: {",
    "  city: string;",
    "  categories: { category: string; total: number }[];",
    "}) {",
    "  const system = `You are a frugal Indian financial advisor.",
    "  Give hyper-local, actionable money-saving tips.",
    "  Respond ONLY with valid JSON array, no markdown, no explanation.",
    "  Format: [{tip:string, saving:number, category:string, difficulty:'easy'|'medium'}]",
    "  Give exactly 5 tips.`;",
    "",
    "  const spend = context.categories",
    "    .map(c => `${c.category}: ₹${c.total}`)",
    "    .join(', ');",
    "",
    "  const prompt = `User in ${context.city}.",
    "  Monthly spend: ${spend}.",
    "  Give 5 Jugaad tips. Focus on telecom, food delivery, subscriptions.`;",
    "",
    "  const raw = await callClaude([{role:'user', content:prompt}], system, 600);",
    "",
    "  try {",
    "    const clean = raw.replace(/```json|```/g, '').trim();",
    "    return JSON.parse(clean) as JugaadTip[];",
    "  } catch {",
    "    return getDefaultJugaadTips();",
    "  }",
    "}",
    "",
    "// ── DOOM SPENDING ANALYSIS ────────────────────────────────────────",
    "export async function analyzeDoom(context: {",
    "  count: number; total: number; merchants: string[];",
    "}) {",
    "  const system = `You are a compassionate financial therapist.",
    "  Explain doom spending using neuroscience in 2 sentences.",
    "  Never blame. Be like a wise, understanding older sibling.`;",
    "",
    "  const prompt = `${context.count} purchases under ₹800 in 48hrs.",
    "  Total ₹${context.total}. From: ${context.merchants.join(', ')}.`,",
    "  `Explain what the brain is doing. 2 sentences only.`;",
    "",
    "  return callClaude([{role:'user', content:prompt}], system, 150);",
    "}",
    "",
    "// ── FALLBACK JUGAAD TIPS (no API needed) ─────────────────────────",
    "function getDefaultJugaadTips(): JugaadTip[] {",
    "  return [",
    "    { tip: 'Switch Jio postpaid ₹999 to prepaid ₹719 — same 2GB/day data',",
    "      saving: 280, category: 'telecom', difficulty: 'easy' },",
    "    { tip: 'Order from Swiggy via ONDC app Magicpin — same restaurants, lower fees',",
    "      saving: 300, category: 'food', difficulty: 'easy' },",
    "    { tip: 'Use HDFC Millennia card for Zomato/Amazon: 5% cashback',",
    "      saving: 500, category: 'credit', difficulty: 'medium' },",
    "    { tip: 'Check for unused UPI Autopay mandates in your payments app',",
    "      saving: 400, category: 'subscription', difficulty: 'easy' },",
    "    { tip: 'DMart Ready weekly basket is ~14% cheaper than quick-commerce',",
    "      saving: 600, category: 'groceries', difficulty: 'easy' },",
    "  ];",
    "}",
    "",
    "export interface JugaadTip {",
    "  tip:        string;",
    "  saving:     number;",
    "  category:   string;",
    "  difficulty: 'easy' | 'medium';",
    "}",
  ]),
  sp(), pgBreak(),
];

// ─── ADD TRANSACTION SCREEN ───────────────────────────────────────────────────
const s10 = [
  h1("File 10 — app/addTransaction.tsx  (The Most Important Screen)"),
  hr(C.acc, 4), sp(),
  body("This is what makes the app REAL. When the user adds a transaction here, it writes to SQLite, updates the balance, and triggers a full store refresh. Every number on every screen updates instantly."),
  sp(),
  fileTag("app/addTransaction.tsx"),
  ...code([
    "import React, { useState } from 'react';",
    "import {",
    "  View, Text, TextInput, TouchableOpacity,",
    "  StyleSheet, ScrollView, Alert,",
    "} from 'react-native';",
    "import { SafeAreaView } from 'react-native-safe-area-context';",
    "import { useNavigation } from '@react-navigation/native';",
    "import * as Haptics from 'expo-haptics';",
    "import { Ionicons } from '@expo/vector-icons';",
    "import { addTransaction } from '../db/queries';",
    "import { useStore } from '../store/useStore';",
    "import { colors, type, card, spacing, radius } from '../theme';",
    "",
    "const CATEGORIES = [",
    "  { key:'food',         label:'Food',          icon:'🍕' },",
    "  { key:'groceries',    label:'Groceries',      icon:'🛒' },",
    "  { key:'transport',    label:'Transport',      icon:'🚗' },",
    "  { key:'rent',         label:'Rent',           icon:'🏠' },",
    "  { key:'emi',          label:'EMI/Loan',       icon:'💳' },",
    "  { key:'subscription', label:'Subscription',   icon:'📱' },",
    "  { key:'medical',      label:'Medical',        icon:'🏥' },",
    "  { key:'entertainment',label:'Entertainment',  icon:'🎮' },",
    "  { key:'other',        label:'Other',          icon:'💸' },",
    "];",
    "",
    "export default function AddTransactionScreen() {",
    "  const nav = useNavigation();",
    "  const { updateBalance } = useStore();",
    "",
    "  const [amount,   setAmount]   = useState('');",
    "  const [merchant, setMerchant] = useState('');",
    "  const [note,     setNote]     = useState('');",
    "  const [category, setCategory] = useState('other');",
    "  const [type,     setType]     = useState<'debit'|'credit'>('debit');",
    "  const [saving,   setSaving]   = useState(false);",
    "",
    "  async function handleSave() {",
    "    const amt = parseFloat(amount);",
    "    if (!amt || amt <= 0) {",
    "      Alert.alert('Enter a valid amount');",
    "      return;",
    "    }",
    "",
    "    setSaving(true);",
    "    try {",
    "      // 1. Write transaction to DB",
    "      await addTransaction({",
    "        amount: amt, type, category, merchant, note,",
    "        txn_date: new Date().toISOString(),",
    "        is_recurring: 0, member_id: 0,",
    "      });",
    "",
    "      // 2. Update running balance in profile",
    "      await updateBalance(amt, type === 'credit' ? 'add' : 'subtract');",
    "",
    "      // 3. Native haptic feedback — makes it feel real",
    "      await Haptics.notificationAsync(",
    "        Haptics.NotificationFeedbackType.Success",
    "      );",
    "",
    "      // 4. Go back — store is already refreshed, home screen updates",
    "      nav.goBack();",
    "    } catch (e) {",
    "      Alert.alert('Error', 'Could not save transaction');",
    "    } finally {",
    "      setSaving(false);",
    "    }",
    "  }",
    "",
    "  return (",
    "    <SafeAreaView style={s.root}>",
    "      <View style={s.header}>",
    "        <TouchableOpacity onPress={() => nav.goBack()}>",
    "          <Ionicons name='close' size={24} color={colors.muted} />",
    "        </TouchableOpacity>",
    "        <Text style={type.h3}>Add Transaction</Text>",
    "        <View style={{ width: 24 }} />",
    "      </View>",
    "",
    "      <ScrollView contentContainerStyle={s.scroll}>",
    "        {/* ── DEBIT / CREDIT TOGGLE ── */}",
    "        <View style={s.typeToggle}>",
    "          {(['debit','credit'] as const).map(t => (",
    "            <TouchableOpacity",
    "              key={t}",
    "              style={[s.typeBtn, type === t && {",
    "                backgroundColor: t === 'debit' ? colors.red + '33' : colors.green + '33',",
    "                borderColor:     t === 'debit' ? colors.red : colors.green,",
    "              }]}",
    "              onPress={() => setType(t)}",
    "            >",
    "              <Text style={{ color: t === 'debit' ? colors.red : colors.green,",
    "                fontFamily: 'DMSans_500Medium', fontSize: 14 }}>",
    "                {t === 'debit' ? '↓ Spent' : '↑ Received'}",
    "              </Text>",
    "            </TouchableOpacity>",
    "          ))}",
    "        </View>",
    "",
    "        {/* ── AMOUNT INPUT ── */}",
    "        <View style={s.amtWrap}>",
    "          <Text style={s.rupee}>₹</Text>",
    "          <TextInput",
    "            style={s.amtInput}",
    "            placeholder='0'",
    "            placeholderTextColor={colors.subtle}",
    "            keyboardType='numeric'",
    "            value={amount}",
    "            onChangeText={setAmount}",
    "            autoFocus",
    "          />",
    "        </View>",
    "",
    "        {/* ── MERCHANT ── */}",
    "        <TextInput",
    "          style={s.input}",
    "          placeholder='Merchant / Paid to (optional)'",
    "          placeholderTextColor={colors.subtle}",
    "          value={merchant}",
    "          onChangeText={setMerchant}",
    "        />",
    "",
    "        {/* ── NOTE ── */}",
    "        <TextInput",
    "          style={s.input}",
    "          placeholder='Note (optional)'",
    "          placeholderTextColor={colors.subtle}",
    "          value={note}",
    "          onChangeText={setNote}",
    "        />",
    "",
    "        {/* ── CATEGORY CHIPS ── */}",
    "        <Text style={[type.label, { marginBottom: 8, marginTop: 16 }]}>",
    "          Category",
    "        </Text>",
    "        <View style={s.chipGrid}>",
    "          {CATEGORIES.map(c => (",
    "            <TouchableOpacity",
    "              key={c.key}",
    "              style={[s.chip, category === c.key && s.chipActive]}",
    "              onPress={() => setCategory(c.key)}",
    "            >",
    "              <Text style={{ fontSize: 16 }}>{c.icon}</Text>",
    "              <Text style={[s.chipLabel,",
    "                category === c.key && { color: colors.accent }",
    "              ]}>{c.label}</Text>",
    "            </TouchableOpacity>",
    "          ))}",
    "        </View>",
    "",
    "        {/* ── SAVE BUTTON ── */}",
    "        <TouchableOpacity",
    "          style={[s.saveBtn, saving && { opacity: 0.6 }]}",
    "          onPress={handleSave}",
    "          disabled={saving}",
    "        >",
    "          <Text style={s.saveTxt}>",
    "            {saving ? 'Saving…' : `Save ${type === 'debit' ? 'expense' : 'income'}`}",
    "          </Text>",
    "        </TouchableOpacity>",
    "      </ScrollView>",
    "    </SafeAreaView>",
    "  );",
    "}",
    "",
    "const s = StyleSheet.create({",
    "  root:      { flex:1, backgroundColor:colors.bg },",
    "  header:    { flexDirection:'row', alignItems:'center',",
    "               justifyContent:'space-between', padding:16 },",
    "  scroll:    { padding:16, paddingBottom:60 },",
    "  typeToggle:{ flexDirection:'row', gap:10, marginBottom:20 },",
    "  typeBtn:   { flex:1, padding:12, borderRadius:radius.md,",
    "               borderWidth:1, borderColor:colors.border,",
    "               alignItems:'center' },",
    "  amtWrap:   { flexDirection:'row', alignItems:'center',",
    "               marginBottom:16 },",
    "  rupee:     { fontSize:36, color:colors.muted,",
    "               fontFamily:'SpaceGrotesk_700Bold', marginRight:4 },",
    "  amtInput:  { flex:1, fontSize:52, color:colors.text,",
    "               fontFamily:'SpaceGrotesk_700Bold' },",
    "  input:     { backgroundColor:colors.s2, borderRadius:radius.md,",
    "               padding:14, color:colors.text, marginBottom:10,",
    "               fontFamily:'DMSans_400Regular', fontSize:15,",
    "               borderWidth:1, borderColor:colors.border },",
    "  chipGrid:  { flexDirection:'row', flexWrap:'wrap', gap:8 },",
    "  chip:      { flexDirection:'row', alignItems:'center', gap:6,",
    "               backgroundColor:colors.s2, borderRadius:radius.full,",
    "               paddingVertical:8, paddingHorizontal:12,",
    "               borderWidth:1, borderColor:colors.border },",
    "  chipActive:{ borderColor:colors.accent, backgroundColor:colors.accent+'22' },",
    "  chipLabel: { fontFamily:'DMSans_500Medium', fontSize:13, color:colors.muted },",
    "  saveBtn:   { backgroundColor:colors.accent, borderRadius:radius.lg,",
    "               padding:16, alignItems:'center', marginTop:32 },",
    "  saveTxt:   { color:'#fff', fontFamily:'SpaceGrotesk_700Bold', fontSize:16 },",
    "});",
  ]),
  sp(), pgBreak(),
];

// ─── BUILD TO APK ─────────────────────────────────────────────────────────────
const s11 = [
  h1("Building the Real APK — Step by Step"),
  hr(C.acc, 4), sp(),
  body("This gets Artha installed on your Android phone as a real native app — no Expo Go required. The process takes about 15 minutes to set up and 10 minutes to build."),
  sp(),

  h2("Step 1 — Install and configure EAS"),
  ...code([
    "# Install EAS CLI globally",
    "npm install -g eas-cli",
    "",
    "# Login (create free account at expo.dev if needed)",
    "eas login",
    "",
    "# In your project folder, initialize EAS",
    "eas build:configure",
    "# Choose: Android only (for now)",
    "# This creates eas.json in your project root",
  ]),

  sp(),
  h2("Step 2 — Configure eas.json"),
  body("Replace your eas.json with this. The 'preview' profile builds a direct-install APK for your own phone."),
  fileTag("eas.json"),
  ...code([
    '{',
    '  "cli": { "version": ">= 12.0.0" },',
    '  "build": {',
    '    "preview": {',
    '      "android": {',
    '        "buildType": "apk",',
    '        "gradleCommand": ":app:assembleRelease"',
    '      }',
    '    },',
    '    "production": {',
    '      "android": {',
    '        "buildType": "app-bundle"',
    '      }',
    '    }',
    '  }',
    '}',
  ]),

  sp(),
  h2("Step 3 — Configure app.json"),
  fileTag("app.json (key fields)"),
  ...code([
    '{',
    '  "expo": {',
    '    "name": "Artha",',
    '    "slug": "artha-finance",',
    '    "version": "1.0.0",',
    '    "orientation": "portrait",',
    '    "icon": "./assets/icon.png",',
    '    "userInterfaceStyle": "dark",',
    '    "splash": {',
    '      "image": "./assets/splash.png",',
    '      "resizeMode": "contain",',
    '      "backgroundColor": "#0C0C12"',
    '    },',
    '    "android": {',
    '      "adaptiveIcon": {',
    '        "foregroundImage": "./assets/adaptive-icon.png",',
    '        "backgroundColor": "#0C0C12"',
    '      },',
    '      "package": "com.artha.finance",',
    '      "permissions": [',
    '        "RECEIVE_BOOT_COMPLETED",',
    '        "VIBRATE"',
    '      ]',
    '    },',
    '    "plugins": [',
    '      "expo-sqlite",',
    '      "expo-notifications",',
    '      "expo-secure-store",',
    '      "expo-haptics",',
    '      "expo-font"',
    '    ]',
    '  }',
    '}',
  ]),

  sp(),
  h2("Step 4 — Build the APK"),
  ...code([
    "# Build for Android (runs on Expo's free cloud servers)",
    "eas build --platform android --profile preview",
    "",
    "# You'll see a build URL. The build takes 8–15 minutes.",
    "# When done, you get a download link for the .apk file",
    "",
    "# Download the APK to your computer",
    "# Transfer to your Android phone (USB cable or Google Drive)",
    "",
    "# On your Android phone:",
    "# Settings → Apps → Special app access → Install unknown apps",
    "# Enable for Files or Chrome (whichever you use to open the APK)",
    "# Tap the APK → Install → Open",
    "",
    "# The app is now installed as a real native app",
    "# No Expo Go. No browser. Just Artha.",
  ]),

  sp(),
  h2("Step 5 — Play Store (when you're ready)"),
  ...code([
    "# 1. Create Google Play Developer account ($25 one-time fee)",
    "#    play.google.com/console",
    "",
    "# 2. Build production bundle (AAB format for Play Store)",
    "eas build --platform android --profile production",
    "",
    "# 3. In Play Console:",
    "#    Create app → Internal testing → Upload AAB",
    "#    Add yourself as tester → Download from Play Store",
    "",
    "# 4. For public release:",
    "#    Fill app details, screenshots, privacy policy",
    "#    Submit for review → 3–7 days for first release",
  ]),
  sp(),

  warn("The app needs a real icon (1024×1024 PNG) and splash screen before Play Store submission. Use Figma or Canva — dark background (#0C0C12), the Artha wordmark in orange."),
  sp(),
  good("Internal testing on Play Store is free, instant, and lets you share with up to 100 testers — use this to test with friends before public launch."),
  sp(), pgBreak(),
];

// ─── WHAT TO BUILD IN ORDER ───────────────────────────────────────────────────
const s12 = [
  h1("Build Order — What to Do First"),
  hr(C.acc, 4), sp(),
  body("Don't try to build everything at once. This order gives you a working app after each session."),
  sp(),
  new Table({
    width: { size: 9360, type: WidthType.DXA }, columnWidths: [960, 1680, 4560, 2160],
    rows: [
      new TableRow({ children: ["Day", "Session", "What you build", "Result"].map(t => new TableCell({
        borders: bdrs("333355"), shading: { fill: "0D1117", type: ShadingType.CLEAR }, margins: cm,
        children: [new Paragraph({ children: [new TextRun({ text: t, font: "Arial", size: 18, bold: true, color: C.acc })] })]
      })) }),
      ...[
        ["1", "2–3 hrs", "package.json → npm install → theme/index.ts → db/schema.ts + queries.ts", "DB is set up, app loads without crashing"],
        ["2", "2–3 hrs", "engine/safeToSpend.ts + dangerWindow.ts + doomDetector.ts + store/useStore.ts", "Financial brain is running, numbers are real"],
        ["3", "2–3 hrs", "App.tsx (navigation) + app/home.tsx", "Home screen shows live Safe to Spend from your real data"],
        ["4", "2 hrs",   "app/addTransaction.tsx", "You can add transactions and the numbers update immediately"],
        ["5", "2 hrs",   "app/forecast.tsx (Danger Window screen)", "30-day forecast is visible and clickable"],
        ["6", "2 hrs",   "ai/claude.ts + app/coach.tsx", "AI coach works, Jugaad tips appear"],
        ["7", "2 hrs",   "app/gig.tsx + app/family.tsx", "Gig tracker and family mode are live"],
        ["8", "1 hr",    "eas build → APK on your phone", "Real installed app, no Expo Go needed"],
        ["9", "1–2 hrs", "App icon, splash screen, polish", "Ready for Play Store internal testing"],
      ].map(([day, time, what, result]) => new TableRow({ children: [day, time, what, result].map((t, i) => new TableCell({
        borders: bdrs("222233"), shading: { fill: i === 0 ? "0D1117" : "000000", type: ShadingType.CLEAR }, margins: cm,
        children: [new Paragraph({ children: [new TextRun({ text: t, font: "Arial", size: 17, bold: i === 0, color: i === 3 ? "86EFAC" : "AAAAAA" })] })]
      })) }))
    ]
  }),
  sp(), sp(),
  hr(C.acc, 8), sp(),
  new Paragraph({ alignment: AlignmentType.CENTER, children: [new TextRun({ text: "ARTHA", font: "Consolas", size: 48, bold: true, color: C.acc })] }),
  new Paragraph({ alignment: AlignmentType.CENTER, spacing: { before: 40 },
    children: [new TextRun({ text: "Build it once. Use it every day.", font: "Arial", size: 22, italics: true, color: "555577" })] }),
];

// ─── ASSEMBLE ─────────────────────────────────────────────────────────────────
const doc = new Document({
  styles: {
    default: { document: { run: { font: "Arial", size: 20, color: "CCCCCC" } } },
    paragraphStyles: [
      { id:"Heading1", name:"Heading 1", basedOn:"Normal", next:"Normal", quickFormat:true,
        run:{ size:40, bold:true, font:"Consolas", color:C.white },
        paragraph:{ spacing:{ before:320, after:120 }, outlineLevel:0 } },
      { id:"Heading2", name:"Heading 2", basedOn:"Normal", next:"Normal", quickFormat:true,
        run:{ size:26, bold:true, font:"Arial", color:C.acc },
        paragraph:{ spacing:{ before:260, after:80 }, outlineLevel:1 } },
      { id:"Heading3", name:"Heading 3", basedOn:"Normal", next:"Normal", quickFormat:true,
        run:{ size:22, bold:true, font:"Arial", color:C.white },
        paragraph:{ spacing:{ before:200, after:60 }, outlineLevel:2 } },
    ]
  },
  numbering: {
    config: [
      { reference:"bul",  levels:[{ level:0, format:LevelFormat.BULLET,  text:"•", alignment:AlignmentType.LEFT, style:{ paragraph:{ indent:{ left:480, hanging:240 } } } }] },
      { reference:"nums", levels:[{ level:0, format:LevelFormat.DECIMAL, text:"%1.", alignment:AlignmentType.LEFT, style:{ paragraph:{ indent:{ left:480, hanging:240 } } } }] },
    ]
  },
  sections: [{
    properties: {
      page: {
        size: { width:12240, height:15840 },
        margin: { top:1080, right:1080, bottom:1080, left:1080 }
      }
    },
    headers: {
      default: new Header({ children: [new Paragraph({
        shading: { fill:"0C0C12", type:ShadingType.CLEAR },
        border: { bottom:{ style:BorderStyle.SINGLE, size:4, color:"2A2A3C", space:1 } },
        tabStops:[{ type:TabStopType.RIGHT, position:TabStopPosition.MAX }],
        children: [
          new TextRun({ text:"ARTHA · Complete Working Codebase", font:"Consolas", size:16, color:"444466" }),
          new TextRun({ text:"\tPersonal Project Edition · 2026", font:"Arial", size:16, color:"333355" }),
        ]
      })] })
    },
    footers: {
      default: new Footer({ children: [new Paragraph({
        border: { top:{ style:BorderStyle.SINGLE, size:4, color:"2A2A3C", space:1 } },
        tabStops:[{ type:TabStopType.RIGHT, position:TabStopPosition.MAX }],
        children: [
          new TextRun({ text:"Every file. Complete. Actually works.", font:"Arial", size:16, italics:true, color:"333355" }),
          new TextRun({ text:"\t© 2026 Artha", font:"Arial", size:16, color:"333355" }),
        ]
      })] })
    },
    children: [
      ...cover, ...s0, ...s1, ...s2, ...s3, ...s4,
      ...s5, ...s6, ...s7, ...s8, ...s9, ...s10,
      ...s11, ...s12,
    ]
  }]
});

Packer.toBuffer(doc)
  .then(buf => {
    fs.writeFileSync('C:\\Users\\Asus\\OneDrive\\Desktop\\Work house\\Project\\Artha AI\\Artha_Complete_Code.docx', buf);
    console.log('Done');
  })
  .catch(e => { console.error(e); process.exit(1); });